### PR TITLE
fix sequence

### PR DESCRIPTION
**Pull request by kevit**
Hello

We have our FQDN on 127.0.0.1, better if localhost entry will be append after fqdn record creating, otherwise no localhost entry in /etc/hosts presented

Regards,
Siarhei

### CODE REVIEW

**Comment by mburns** [comment]
The second commit should be removed, but 0c26b3f is a reasonable fix. :+1:, fwiw.

**Comment by nathantsoi** [comment]
thx for the input @mburns. could you fix the conflicts as well plz, @kevit?

**Comment by kevit** [comment]
I am not sure how to make merge request using only 0c26b3f. Any ideas?

**Comment by nathantsoi** [comment]
@kevit, cut a new branch and make sure that  https://github.com/nathantsoi/chef-cookbook-hostname/commit/0c26b3fb9e59cb7df786341f4fdd0801c0ffc0a8 is the only change vs. master

here's how i would do it

cd to your source directory and run something like:

```
git checkout fix-run-sequence
git reset --hard upstream/master # where upstream is the name of my remote
# if you need to add my code as a remote: help.github.com/articles/adding-a-remote/
git cherry-pick 0c26b3fb9e59cb7df786341f4fdd0801c0ffc0a8
git push origin fix-run-sequence
# open a new pull request w/ your fix-run-sequence against my master 
```

or just `git reset --hard 0c26b3fb9e59cb7df786341f4fdd0801c0ffc0a8 && git push -f` which will undo the metadata.rb change and update github

**Comment by nathantsoi** [comment]
no worries, ill add https://github.com/nathantsoi/chef-cookbook-hostname/commit/0c26b3fb9e59cb7df786341f4fdd0801c0ffc0a8

**Pull request closed without merging**
